### ISSUE TITLE
Manage authentication for Mesos/Marathon/Chronos endpoints

### ISSUE THREAD

**Issue by maricaantonacci** [indigo-dc/ansible-role-clues#1]
It should be possible to customize the curl command inside /etc/clues2/conf.d/plugin-mesos.cfg in case of authentication and SSL support enabled for the cluster endpoints.

**Comment by micafer** [comment]
Hi @maricaantonacci this is not a problem of the clues role. It is a problem if the mesos clues plugin.
I have opened an inssue in the proper place. Please subscribe to t
https://github.com/indigo-dc/clues-indigo/issues/20
