### ISSUE TITLE
Resolution of the name mesosserverpublic 

### ISSUE THREAD

**Issue by maricaantonacci** [indigo-dc/ansible-role-clues#3]
The role uses the name "mesosserverpublic" to contact the Mesos master endpoints. However, this name is not included in the /etc/hosts file and therefore it is not resolved by cluesserver.

**Comment by micafer** [comment]
@maricaantonacci. The role expects that the mesos master uses this name. You can set it in the TOSCA document as we do in other elastic clusters. See for example: https://github.com/indigo-dc/tosca-types/blob/master/examples/galaxy_elastic_cluster.yaml#L94
Adding this line mesosserverpublic will appear in the /etc/hosts with the correct IP address.
In the future we can see how to address it in a more general way.

**Comment by micafer** [comment]
I proposed a pull request with this change:
https://github.com/indigo-dc/tosca-types/pull/109
If you agree we can merge it and close this issue.
